// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Data;

#nullable disable

namespace SalesManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422030816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Manager",
                            Date = "2026-04-25",
                            Message = "Quarterly Sales Meeting on Friday at 10 AM."
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Manager",
                            Date = "2026-04-20",
                            Message = "New commission structure implemented from next month."
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChanceToClose")
                        .HasColumnType("int");

                    b.Property<string>("ContactMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("Proposals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 45000m,
                            ChanceToClose = 80,
                            ContactMobile = "1234567890",
                            ContactName = "John Doe",
                            CreatedUserId = 2,
                            Description = "Full stack cloud migration for enterprise client.",
                            Duration = 60,
                            EstimatedBudget = 50000m,
                            IsAccepted = true,
                            Name = "Enterprise Cloud Solution",
                            Notes = "High priority project.",
                            RejectionReason = "",
                            Revenue = 9000m,
                            Timestamp = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 14000m,
                            ChanceToClose = 50,
                            ContactMobile = "0987654321",
                            ContactName = "Jane Smith",
                            CreatedUserId = 3,
                            Description = "UI/UX redesign of existing mobile app.",
                            Duration = 30,
                            EstimatedBudget = 15000m,
                            IsAccepted = false,
                            Name = "Mobile App Revamp",
                            Notes = "Tight deadline.",
                            RejectionReason = "Budget mismatch",
                            Revenue = 3000m,
                            Timestamp = new DateTime(2026, 4, 15, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "manager",
                            Role = "Manager",
                            Username = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Password = "sales@01",
                            Role = "Sales",
                            Username = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Password = "pravin",
                            Role = "Sales",
                            Username = "Pravin"
                        });
                });

            modelBuilder.Entity("SalesManagement.Models.Proposal", b =>
                {
                    b.HasOne("SalesManagement.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
